services:
  db:
    image: postgres:17
    container_name: simad-postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: simad_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - simad-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d simad_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:

networks:
  simad-network:
    driver: bridge
